---
- name: Create certbot user
  user:
    name:  '{{ certbot_user }}'
    group: '{{ certbot_group }}'
    uid:   '{{ certbot_user_uid }}'

- name: Fix LetsEncrypt folder permissions
  file:
    path:  '{{ item }}'
    owner: '{{ certbot_user }}'
    group: '{{ certbot_group }}'
    mode:  0770
    recurse: true
  with_items:
    - '{{ certbot_config_dir }}'
    - '{{ certbot_work_dir }}'
    - '{{ certbot_logs_dir }}'

- name: Create docker wrapper for certbot
  template:
    src: 'certbot.sh.j2'
    dest: '{{ certbot_entrypoint }}'
    mode: 0755
