---
- name: Check if certificate already exists.
  stat:
    path: '{{ certbot_config_dir }}/live/{{ cert_item.domains | first | replace("*.", "") }}/cert.pem'
  register: letsencrypt_cert

- name: Fix LetsEncrypt folder permissions
  file:
    path: '{{ item }}'
    owner: '{{ certbot_docker_enabled | ternary(certbot_docker_cont_uid, "root") }}'
    group: '{{ certbot_docker_enabled | ternary("dockremap", "root") }}'
    mode: 0770
    recurse: true
  with_items:
    - '{{ certbot_config_dir }}'
    - '{{ certbot_work_dir }}'
    - '{{ certbot_logs_dir }}'

- when: not letsencrypt_cert.stat.exists
  block:
    - name: Stop services to allow certbot to generate a cert.
      service:
        name: '{{ item }}'
        state: 'stopped'
      with_items: '{{ certbot_services_to_stop }}'
      # Service might not yet exist.
      ignore_errors: true

    - name: Stop contrainers to allow certbot to generate a cert.
      docker_container:
        name: '{{ item }}'
        state: 'stopped'
      with_items: '{{ certbot_containers_to_stop }}'
      ignore_errors: true

    - name: Generate new certificate if one doesn't exist.
      command: '{{ certbot_entrypoint }} {{ certbot_create_arguments }}'

    - name: Start services after cert has been generated.
      service:
        name: '{{ item }}'
        state: 'started'
      with_items: '{{ certbot_services_to_stop }}'
      ignore_errors: true

    - name: Start containers after cert has been generated.
      docker_container:
        name: '{{ item }}'
        state: 'started'
      with_items: '{{ certbot_containers_to_stop }}'
      ignore_errors: true
