---
- name: Install Certbot.
  package:
    name: certbot
  when: not certbot_docker_enabled

- name: Create docker wrapper for certbot
  template:
    src: 'certbot.sh.j2'
    dest: '{{ certbot_entrypoint }}'
    mode: 0755
  when: certbot_docker_enabled
