---
- name: Install Certbot.
  package:
    name: certbot
  when: not certbot_docker_enabled

- name: Create docker wrapper for certbot
  copy:
    dest: '{{ certbot_entrypoint }}'
    mode: 0755
    content: |
      #!/usr/bin/env bash
      exec docker run -i --rm \
        --name='{{ certbot_docker_cont_name }}' \
        -v '{{ certbot_certs_dir }}:{{ certbot_certs_dir }}' \
        -p '80:80/tcp' -p '443:443/tcp' \
        '{{ certbot_docker_cont_image }}' \
        "$@"
  when: certbot_docker_enabled
