---
- name: Create certbot renewal timer
  include_role: name=systemd-timer
  vars:
    systemd_timer_name: 'certbot-renew'
    systemd_timer_description: 'LetsEncrypt certificate renewal via certbot.'
    systemd_timer_user: 'root'
    systemd_timer_work_dir: '{{ certbot_certs_dir }}'
    systemd_timer_frequency: '{{ certbot_auto_renew_frequency }}'
    systemd_timer_timeout_sec: '{{ certbot_auto_renew_timeout_sec }}'
    systemd_timer_start_on_creation: false
    systemd_timer_script_path: '{{ certbot_entrypoint }}'
    systemd_timer_script_args: 'renew'
    systemd_timer_exec_start_pre: |
      {{ (["docker stop "]     | product(certbot_containers_to_stop) | map("join")) +
         (["systemctl stop "]  | product(certbot_services_to_stop)   | map("join")) }}
    systemd_timer_exec_start_post: |
      {{ (["docker start "]    | product(certbot_containers_to_stop) | map("join")) +
         (["systemctl start "] | product(certbot_services_to_stop)   | map("join")) }}
